// Import images
import americanoImg from '../assets/img/61790277.jpg';
import creamyCocoaImg from '../assets/img/61790278.jpg';
import cafeLattesImg from '../assets/img/61790279.jpg';
import spanishLatteImg from '../assets/img/61790280.jpg';
import vanillaLatteImg from '../assets/img/61790281.jpg';
import caramelLatteImg from '../assets/img/61790282.jpg';
import whiteMochaImg from '../assets/img/61790283.jpg';
import javaChipsImg from '../assets/img/61790284.jpg';
import einspannerLatteImg from '../assets/img/61790285.jpg';
import matchaLatteImg from '../assets/img/61790286.jpg';
import merryMatchaImg from '../assets/img/61790287.jpg';
import strawberryMatchaImg from '../assets/img/61790288.jpg';
import matchaEspressoImg from '../assets/img/61790289.jpg';
import ubeTaroImg from '../assets/img/61790290.jpg';
import strawberryImg from '../assets/img/61790291.jpg';
import darkCocoaImg from '../assets/img/61790292.jpg';
import pinkLycheeImg from '../assets/img/61790294.jpg';
import purpleLemonadeImg from '../assets/img/61790295.jpg';
import cappuccinoImg from '../assets/img/61790296.jpg';

// Coffee product data
export const products = [
   {
      id: 1,
      name: 'Americano',
      price: 49,
      originalPrice: 99,
      category: 'coffee',
      categoryQuality: 'premium',
      image: americanoImg,
      description:
         'Bold and invigorating, this classic drink combines rich espresso with chilled water and ice for a refreshing, smooth, and energizing coffee experience.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced', 'hot'],
      defaultTemperature: 'iced',
      rating: 4.8,
      reviewCount: 124,
      caffeine: 'high',
      ingredients: ['espresso', 'water'],
      nutritionalInfo: {
         calories: 15,
         sugar: '0g',
         fat: '0g',
      },
   },
   {
      id: 2,
      name: 'Cafe Latte',
      price: 49,
      originalPrice: 99,
      category: 'coffee',
      categoryQuality: 'premium',
      image: cafeLattesImg,
      description:
         'A classic blend of rich espresso and creamy milk, served over ice for a smooth and refreshing coffee experience. Perfectly light and satisfying.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced', 'hot'],
      defaultTemperature: 'iced',
      rating: 4.7,
      reviewCount: 156,
      caffeine: 'medium',
      ingredients: ['espresso', 'milk'],
      nutritionalInfo: {
         calories: 120,
         sugar: '10g',
         fat: '5g',
      },
   },
   {
      id: 3,
      name: 'Spanish Latte',
      price: 49,
      originalPrice: 99,
      category: 'coffee',
      categoryQuality: 'premium',
      image: spanishLatteImg,
      description:
         'A luscious combination of bold espresso, creamy milk, and a hint of sweetness, served over ice. This indulgent drink offers a perfectly balanced and refreshing coffee treat.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced', 'hot'],
      defaultTemperature: 'iced',
      rating: 4.9,
      reviewCount: 98,
      caffeine: 'medium',
      ingredients: ['espresso', 'milk', 'condensed milk'],
      nutritionalInfo: {
         calories: 180,
         sugar: '20g',
         fat: '6g',
      },
   },
   {
      id: 4,
      name: 'Vanilla Latte',
      price: 49,
      originalPrice: 99,
      category: 'coffee',
      categoryQuality: 'premium',
      image: vanillaLatteImg,
      description:
         'A refreshing blend of smooth espresso, creamy milk, and a touch of sweet vanilla syrup, served over ice. Perfectly balanced for a delightful pick-me-up on warm days.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced', 'hot'],
      defaultTemperature: 'iced',
      rating: 4.6,
      reviewCount: 142,
      caffeine: 'medium',
      ingredients: ['espresso', 'milk', 'vanilla syrup'],
      nutritionalInfo: {
         calories: 160,
         sugar: '22g',
         fat: '5g',
      },
   },
   {
      id: 5,
      name: 'Caramel Latte',
      price: 49,
      originalPrice: 99,
      category: 'coffee',
      categoryQuality: 'premium',
      image: caramelLatteImg,
      description:
         'Smooth espresso paired with creamy milk and sweet caramel syrup, served over ice.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced', 'hot'],
      defaultTemperature: 'iced',
      rating: 4.7,
      reviewCount: 135,
      caffeine: 'medium',
      ingredients: ['espresso', 'milk', 'caramel syrup'],
      nutritionalInfo: {
         calories: 190,
         sugar: '26g',
         fat: '5g',
      },
   },
   {
      id: 6,
      name: 'White Mocha',
      price: 49,
      originalPrice: 99,
      category: 'coffee',
      categoryQuality: 'premium',
      image: whiteMochaImg,
      description:
         'A delightful mix of bold espresso, creamy milk, and sweet white chocolate syrup, served over ice.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced', 'hot'],
      defaultTemperature: 'iced',
      rating: 4.8,
      reviewCount: 118,
      caffeine: 'medium-high',
      ingredients: ['espresso', 'milk', 'white chocolate syrup'],
      nutritionalInfo: {
         calories: 220,
         sugar: '28g',
         fat: '7g',
      },
   },
   {
      id: 7,
      name: 'Java Chips',
      price: 49,
      originalPrice: 99,
      category: 'coffee',
      categoryQuality: 'premium',
      image: javaChipsImg,
      description:
         'A deliciously indulgent blend of rich coffee, chocolate chips, and creamy milk, all served over ice. A perfect treat for coffee and chocolate lovers, offering a smooth and satisfying crunch in every sip.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced'],
      defaultTemperature: 'iced',
      rating: 4.9,
      reviewCount: 167,
      caffeine: 'medium-high',
      ingredients: ['coffee', 'milk', 'chocolate chips', 'chocolate syrup'],
      customizable: true,
      nutritionalInfo: {
         calories: 310,
         sugar: '32g',
         fat: '14g',
      },
   },
   {
      id: 8,
      name: 'Einspanner Latte',
      price: 49,
      originalPrice: 99,
      category: 'coffee',
      categoryQuality: 'premium',
      image: einspannerLatteImg,
      description:
         'A bold espresso paired with chilled milk, topped with a thick layer of whipped cream, and served over ice. A rich and creamy coffee treat with a smooth, indulgent finish.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced', 'hot'],
      defaultTemperature: 'iced',
      rating: 4.7,
      reviewCount: 92,
      caffeine: 'medium',
      ingredients: ['espresso', 'milk', 'whipped cream'],
      nutritionalInfo: {
         calories: 210,
         sugar: '16g',
         fat: '12g',
      },
   },
   {
      id: 9,
      name: 'Matcha Latte',
      price: 49,
      originalPrice: 99,
      category: 'matcha',
      categoryQuality: 'ceremonial grade',
      image: matchaLatteImg,
      description:
         'A refreshing blend of premium matcha green tea and creamy milk, served over ice. Smooth, earthy, and naturally energizing.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced', 'hot'],
      defaultTemperature: 'iced',
      rating: 4.6,
      reviewCount: 128,
      caffeine: 'medium',
      ingredients: ['matcha powder', 'milk'],
      nutritionalInfo: {
         calories: 160,
         sugar: '14g',
         fat: '5g',
      },
   },
   {
      id: 10,
      name: 'Merry Matcha',
      price: 49,
      originalPrice: 99,
      category: 'matcha',
      categoryQuality: 'ceremonial grade',
      image: merryMatchaImg,
      description:
         'A refreshing blend of premium matcha green tea and creamy milk, served over ice and topped with a velvety layer of foam.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced', 'hot'],
      defaultTemperature: 'iced',
      rating: 4.5,
      reviewCount: 86,
      caffeine: 'medium',
      ingredients: ['matcha powder', 'milk', 'foam'],
      nutritionalInfo: {
         calories: 170,
         sugar: '15g',
         fat: '6g',
      },
   },
   {
      id: 11,
      name: 'Strawberry Matcha',
      price: 49,
      originalPrice: 99,
      category: 'matcha',
      categoryQuality: 'premium blend',
      image: strawberryMatchaImg,
      description:
         'A delightful fusion of sweet strawberry, earthy matcha green tea, and creamy milk, served over ice. A vibrant and refreshing treat with layers of flavor.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced'],
      defaultTemperature: 'iced',
      rating: 4.8,
      reviewCount: 112,
      caffeine: 'medium',
      ingredients: ['matcha powder', 'milk', 'strawberry syrup'],
      nutritionalInfo: {
         calories: 200,
         sugar: '26g',
         fat: '5g',
      },
   },
   {
      id: 12,
      name: 'Matcha Espresso',
      price: 49,
      originalPrice: 99,
      category: 'matcha',
      categoryQuality: 'premium blend',
      image: matchaEspressoImg,
      description:
         'A bold combination of smooth espresso and rich matcha green tea, blended with creamy milk and served over ice. A perfect balance of earthy and energizing flavors for a refreshing boost.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced', 'hot'],
      defaultTemperature: 'iced',
      rating: 4.7,
      reviewCount: 94,
      caffeine: 'high',
      ingredients: ['matcha powder', 'espresso', 'milk'],
      nutritionalInfo: {
         calories: 180,
         sugar: '16g',
         fat: '5g',
      },
   },
   {
      id: 13,
      name: 'Ube Taro',
      price: 49,
      originalPrice: 99,
      category: 'milk',
      categoryQuality: 'signature',
      image: ubeTaroImg,
      description:
         'A creamy and refreshing blend of sweet ube and taro, mixed with smooth milk and served over ice. A deliciously vibrant drink with a unique, nutty flavor and a hint of sweetness.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced', 'hot'],
      defaultTemperature: 'iced',
      rating: 4.9,
      reviewCount: 143,
      caffeine: 'none',
      ingredients: ['ube', 'taro', 'milk'],
      nutritionalInfo: {
         calories: 230,
         sugar: '28g',
         fat: '6g',
      },
   },
   {
      id: 14,
      name: 'Strawberry',
      price: 49,
      originalPrice: 99,
      category: 'milk',
      categoryQuality: 'classic',
      image: strawberryImg,
      description:
         'A sweet and creamy blend of fresh strawberry jam and smooth milk, served over ice.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced'],
      defaultTemperature: 'iced',
      rating: 4.6,
      reviewCount: 109,
      caffeine: 'none',
      ingredients: ['strawberry jam', 'milk'],
      nutritionalInfo: {
         calories: 210,
         sugar: '30g',
         fat: '5g',
      },
   },
   {
      id: 15,
      name: 'Dark Cocoa',
      price: 49,
      originalPrice: 99,
      category: 'milk',
      categoryQuality: 'premium',
      image: darkCocoaImg,
      description:
         'A rich and indulgent blend of smooth dark cocoa and creamy milk, served over ice. A refreshing, chocolatey treat with a deep, velvety flavor.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced', 'hot'],
      defaultTemperature: 'iced',
      rating: 4.7,
      reviewCount: 126,
      caffeine: 'low',
      ingredients: ['dark cocoa powder', 'milk'],
      nutritionalInfo: {
         calories: 200,
         sugar: '24g',
         fat: '7g',
      },
   },
   {
      id: 17,
      name: 'Pink Lychee',
      price: 39,
      originalPrice: 79,
      category: 'juice',
      categoryQuality: 'signature',
      image: pinkLycheeImg,
      description:
         'A refreshing mix of tangy lemonade and sweet lychee, served over ice. This vibrant, fruity drink offers a perfect balance of sweetness and citrus, making it a refreshing and exotic treat.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced'],
      defaultTemperature: 'iced',
      rating: 4.7,
      reviewCount: 98,
      caffeine: 'none',
      ingredients: ['lemonade', 'lychee syrup'],
      nutritionalInfo: {
         calories: 140,
         sugar: '32g',
         fat: '0g',
      },
   },
   {
      id: 18,
      name: 'Purple Lemonade',
      price: 39,
      originalPrice: 79,
      category: 'juice',
      categoryQuality: 'signature',
      image: purpleLemonadeImg,
      description:
         'A refreshing and tangy blend of zesty lemon and vibrant red tea, served over ice.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['iced'],
      defaultTemperature: 'iced',
      rating: 4.6,
      reviewCount: 87,
      caffeine: 'low',
      ingredients: ['lemon juice', 'red tea', 'simple syrup'],
      nutritionalInfo: {
         calories: 120,
         sugar: '28g',
         fat: '0g',
      },
   },
   {
      id: 19,
      name: 'Creamy Cocoa',
      price: 39,
      originalPrice: 79,
      category: 'hot',
      categoryQuality: 'premium',
      image: creamyCocoaImg,
      description:
         "A rich and velvety blend of smooth cocoa and creamy milk, perfectly heated to offer a warm and indulgent treat. A comforting drink that's sweet, chocolaty, and irresistibly cozy.",
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['hot'],
      defaultTemperature: 'hot',
      rating: 4.8,
      reviewCount: 112,
      caffeine: 'low',
      ingredients: ['cocoa powder', 'milk', 'whipped cream'],
      nutritionalInfo: {
         calories: 220,
         sugar: '26g',
         fat: '9g',
      },
   },
   {
      id: 20,
      name: 'Cappuccino',
      price: 39,
      originalPrice: 79,
      category: 'hot',
      categoryQuality: 'premium',
      image: cappuccinoImg,
      description:
         'A classic espresso-based drink with equal parts rich espresso, creamy steamed milk, and light foam on top. A smooth, balanced, and aromatic coffee.',
      sizes: ['small', 'medium', 'large'],
      defaultSize: 'medium',
      temperatures: ['hot'],
      defaultTemperature: 'hot',
      rating: 4.7,
      reviewCount: 145,
      caffeine: 'medium-high',
      ingredients: ['espresso', 'steamed milk', 'milk foam'],
      nutritionalInfo: {
         calories: 140,
         sugar: '10g',
         fat: '5g',
      },
   },
];

// Helper functions to get data in different formats
export const getProductsByCategory = (category) => {
   return products.filter((product) => product.category === category);
};

export const getAllCategories = () => {
   return [...new Set(products.map((product) => product.category))];
};

export const getProductById = (id) => {
   return products.find((product) => product.id === id);
};

// Export default products for simple import
export default products;
